site_name: Sabancı University SuperComputing Center
nav:
    - Quickstart: index.md
    - Scheduling with Slurm: slurm.md
    - Tutorials:
        - Using Tosun Cluster: tosun-index.md
        - Using SunHPC Cluster: sunhpc-index.md
        - Available Tools:
            - Matlab: 
                - General Information: matlab/matlab.md
                - Tutorial: matlab/pdf/matlab-tutorial.pdf
                - Slurm Wrapper Files: matlab/pdf/matlab-parallel-slurm-plugin-main.zip
            - Materials Studio: 
                - General Information: ms/ms.md
                - Tutorial: ms/pdf/ms-tutorial.pdf
            - Comsol:
                - General Information: comsol/comsol.md
                - Tutorial: comsol/pdf/comsol-tutorial.pdf
            - Namd: 
                - General Information: namd/namd.md
                - Tutorial: namd/pdf/namd-tutorial.pdf
            - Tensorflow:
                - General Information: tensorflow/tensorflow.md
                - Tutorial: tensorflow/pdf/tensorflow-tutorial.pdf
    - FAQ: faq.md
    - Performance Optimization Tips: performance.md
    - SU-HPC Kullanım Politikası (Turkish): HPC_Kullanım_Politikası.md
    - Feragatname (Turkish): Feragetname.md
    - Help: help.md
theme: readthedocs
